language: generic
sudo: true
dist: precise

os:
  - linux
  - osx

before_install:
    - if [[ $TRAVIS_OS_NAME == osx ]]; then
        brew update > /dev/null;
        brew install fpc > /dev/null;
      else
        sudo apt -q install fpc;
      fi

install:
  - fpc ftreapapp.lpr
  
script:
  - ./ftreapapp
