language: c
sudo: true
dist: xenial

os:
  - linux
  - osx
  - windows

osx_image: xcode10.2

before_install:
    - if [[ $TRAVIS_OS_NAME == osx ]]; then
        brew update > /dev/null;
        brew install fpc > /dev/null;
      elif [[ $TRAVIS_OS_NAME == linux ]]; then
        sudo add-apt-repository "deb http://archive.ubuntu.com/ubuntu $(lsb_release -sc) universe";
        sudo apt-get update;
        sudo apt -q install fpc;
      else
        wget -q ftp://ftp.freepascal.org/pub/fpc/snapshot/v33/i386-win32/fpc-3.3.1.i386-win32.zip;
        mkdir fpc;
        unzip -q -d fpc fpc-3.3.1.i386-win32.zip;
        export PATH="$PATH":"$PWD/fpc/bin/i386-win32/";
        fpcmkcfg -d basepath="$PWD/fpc" -o ./fpc.cfg;
      fi

install:
  - fpc ftreapapp.lpr
  - fpc -O3 -XX -CX ftreapbench.lpr
  
script:
  - ./ftreapapp
  - ./ftreapbench
