language: c
sudo: true
dist: xenial

os:
  - linux
  - osx
  - windows

before_install:
    - if [[ $TRAVIS_OS_NAME == osx ]]; then
        brew update > /dev/null;
        brew install fpc > /dev/null;
      elif [[ $TRAVIS_OS_NAME == linux ]]; then
        sudo add-apt-repository "deb http://archive.ubuntu.com/ubuntu $(lsb_release -sc) universe";
        sudo apt-get update;
        sudo apt -q install fpc;
      else
        wget "https://github.com/newpascal/newpascal/releases/download/np-v1.0.56/newpascal.zip";
        unzip -qq newpascal.zip;
        ./newpascal/configure.bat;
        export PATH="$PATH":"$PWD/newpascal/fpc/bin/i386-win32/";
      fi

install:
  - fpc ftreapapp.lpr
  
script:
  - ./ftreapapp


