language: generic
sudo: true
dist: xenial

os:
  - linux
  - osx

before_install:
    - if [[ $TRAVIS_OS_NAME == osx ]]; then
        brew update > /dev/null;
        brew install fpc > /dev/null;
      else
        sudo add-apt-repository "deb http://archive.ubuntu.com/ubuntu $(lsb_release -sc) universe";
        sudo apt-get update;
        sudo apt -q install fpc;
      fi

install:
  - fpc ftreapapp.lpr
  
script:
  - ./ftreapapp
